version: '3.1'



services:
  joomla:
    image: joomla
    restart: always
    depends_on:
      - "joomladb"
    networks:
      - produciton-network
    ports:
      - "80:80"
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: example


  joomladb:
    image: mysql:5.6
    restart: always
    ports:
      - "3306:3306"
    networks:
      - produciton-network
    environment:
      MYSQL_ROOT_PASSWORD: example

  joomlaftp:
    image: delfer/alpine-ftp-server
    restart: always
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    networks:
      - produciton-network
    environment:
      USERS: "one|1234"

networks:
  produciton-network:
    driver: bridge
